#! /usr/bin/env python3

"""
regex.py -- version 100000.0
Practice script for renaming parts of .fasta files using regular expressions.
Usage: regex.py

Inputs look like this:
>6573_0:0055ae {"pub_gene_id":"A0A210PI52_MIZYE", "pub_og_id":"6310at6447", "og_name":"Transcription factor Sp4","level":6447, "description":"Transcription factor Sp4"}
MTSVTARRNNQEYVVPSSTSQEVQPSPLALLAATCSKIGAPPPTPTEEGNNPTGGTQVRVIGQGSGEGAVAPTWIQLANGAIVDASGKQQTIGIPIQAAGAQPQLITSVIPQFQTVNVDGQEAIFIPSSGVGGGQTILAGNQQQVYTTPTGQIIRQGLPTGSMIPNMGYNLAGNMVNIGGNVVSLAGVQGLQNRPHGVVQAVQMPQQMQQMSNLIQIPVSTSNGQSTYQTIQLPSMQGFPMAFPQGQQATPQLQALSVNTSGVGQGSAGQITTVGNQQVTQVPQPQLIEIAAATTVKSQSDGSKPSTPQSQPTIASQATTTPVLQSSQQNNAGAIMTAGSFSATPGTPNILSQMPTLVPIGTNFINTATGQVIPMSQAMGTNGQNVIVASMTQQSGSSSTTTTSATSTVASTQQQPPSLVQAIPQQITVQALPSQNFANLQFAGQNQVIAQNPWLSALNVANIRAPSMQTIQVPNLQSLQNIQGIQAVQNVQGLQGFQITPQGQLIATGNVQNMGAVTLTPSGGLTVANAVGNNTQQQQQPSPQQFTATIQNVATQLTTGQTGQTLAGTPQIIAAGQQIQQDPNDPTKWQVVQTSQGAAVTLSPSQVSQQGVSVLGEQSVTSNRRLRRVACTCPNCTDNEGRTGENKKKQHICHIPGCKKVYGKTSHLRAHLRWHTGERPFVCNWMFCGKRFTRSDELQRHKRTHTGEKRFECKECKKKFMRSDHLSKHRKTHFNKKAGPNLDHSGNGEEDEGEMIEGGTMVMIECDDDGTEDGAEASFEVTDDDIDVQ

The output should look like this:
>Homo_sapiens:6573_0:0055ae
MTSVTARRNNQEYVVPSSTSQEVQPSPLALLAATCSKIGAPPPTPTEEGNNPTGGTQVRVIGQGSGEGAVAPTWIQLANGAIVDASGKQQTIGIPIQAAGAQPQLITSVIPQFQTVNVDGQEAIFIPSSGVGGGQTILAGNQQQVYTTPTGQIIRQGLPTGSMIPNMGYNLAGNMVNIGGNVVSLAGVQGLQNRPHGVVQAVQMPQQMQQMSNLIQIPVSTSNGQSTYQTIQLPSMQGFPMAFPQGQQATPQLQALSVNTSGVGQGSAGQITTVGNQQVTQVPQPQLIEIAAATTVKSQSDGSKPSTPQSQPTIASQATTTPVLQSSQQNNAGAIMTAGSFSATPGTPNILSQMPTLVPIGTNFINTATGQVIPMSQAMGTNGQNVIVASMTQQSGSSSTTTTSATSTVASTQQQPPSLVQAIPQQITVQALPSQNFANLQFAGQNQVIAQNPWLSALNVANIRAPSMQTIQVPNLQSLQNIQGIQAVQNVQGLQGFQITPQGQLIATGNVQNMGAVTLTPSGGLTVANAVGNNTQQQQQPSPQQFTATIQNVATQLTTGQTGQTLAGTPQIIAAGQQIQQDPNDPTKWQVVQTSQGAAVTLSPSQVSQQGVSVLGEQSVTSNRRLRRVACTCPNCTDNEGRTGENKKKQHICHIPGCKKVYGKTSHLRAHLRWHTGERPFVCNWMFCGKRFTRSDELQRHKRTHTGEKRFECKECKKKFMRSDHLSKHRKTHFNKKAGPNLDHSGNGEEDEGEMIEGGTMVMIECDDDGTEDGAEASFEVTDDDIDVQ
"""

# Import the required packages: sys for operator errors and re for regular expressions
import sys
import re

# Create a variable representing the intended file name and open that file for reading
InFileName="regex.practice1.fasta"
InFile = open(InFileName, 'r')

# Create a regular expression to read the input file name and make a new file name based on that.
m = re.search('(.*).fasta',InFileName)
outfilename = m.group(1)+'.condensed.fasta'

# Open a blank file for writing
outfile = open(outfilename, 'w')

# For each line, if it begins with >, use a regex to capture the desired parts and create a new variable with a more appropriate, condensed name and write this to the new file.
# Otherwise, capture the line and write it to the new file as is.
for each in InFile:
	find = re.search('^[(>)(\S+)](\S+)\s',each)
	if '>' in find.group(0):
		name = ">Homo_sapiens:"+find.group(1)+'\n'
		print(name.strip('\n'))
		outfile.write(name)
	else:
		print(find.group(0))
		outfile.write(find.group(0)) #.strip('\n')) +'\n')

# Close the file. It's just polite.
InFile.close()
